http:
  port: 8090
  host: 'localhost'

db:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: '12345678'
  database: 'nest-dev'
  # 自动同步数据库结构
  synchronize: false
  # 打印数据库日志
  logging: true
  # 自动加载实体
  autoLoadEntities: true

email:
  host: 'smtp.gmail.com'
  port: 587
  username: ''

cookie:
  secret: 'Jsd4JUfwe'

# 文件上传配置
file:
  url: '/Volumes/aoe/web-design/pers-code/file-service'

jwt:
  secret: 'Jsd4JUfwe'
  expiresIn: '1d'

wxin:
  appId: 'wx7fb087be0bf0e244'
  appSecret: '893202baf88591d07be41a2a111b1acf'
